# Generated by Django 5.2.1 on 2026-05-14 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchReportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('total_loans', models.PositiveIntegerField(default=0)),
                ('processed_loans', models.PositiveIntegerField(default=0)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('input_file', models.FileField(upload_to='batch_jobs/input/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='batch_jobs/output/')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
