# Generated by Django 5.2.1 on 2026-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0001_batch_report_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchreportjob',
            name='access_token',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
    ]
